version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/app:rw
    ports:
      - "3000:3000"
    command:
      sh -c "python3 main.py -e prod"
    restart: always
    depends_on:
      - db_idp
      - redis
  db_idp:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=faisal
      - POSTGRES_DB=sso_idp
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
  


  redis:
    image: "redis:alpine"
    ports:
     - 6379:6379
    restart: always
    volumes:
      - redis-data:/data
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 10s
      retries: 3
  celery_worker:
    container_name: celery_worker
    build: .
    volumes:
      - .:/app
    command: celery worker -A celery_worker.celery --loglevel=INFO -P eventlet
    environment:
      - CELERY_BROKER_URL=redis://:Attech123@18.134.217.103:6379/0
      - CELERY_RESULT_BACKEND=redis://:Attech123@18.134.217.103:6379/0
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=faisal
      - POSTGRES_DB=sso_idp
      - DATABASE_URL=postgresql://postgres:faisal@18.134.217.103:5432/sso_idp_1
    depends_on:
      - redis
      - db_idp
volumes:
  redis-data:
  postgres-data:
                
